name: "tekken-space"

services:
  database:
    image: postgres:17.4
    env_file: ./.env.production
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /var/tekken/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    image: ghcr.io/rherwig/tekken-space-web:latest
    depends_on:
      - database
    volumes:
      - /var/tekken/frontend/.env:/app/apps/web/.env

  proxy:
    image: ghcr.io/rherwig/tekken-space-proxy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/tekken/proxy:/data
    depends_on:
      - web

  bot:
    image: ghcr.io/rherwig/tekken-space-bot:latest
    volumes:
      - /var/tekken/bot/.env:/app/.env
