version: '3.8'

services:
    database:
        image: postgres
        env_file: ./.env
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - ./var/data:/var/lib/postgresql/data

    frontend:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "3000:3000"
        depends_on:
            - database
        env_file: ./.env
        environment:
            - DATABASE_URL=${PRISMA_CONNECTION_STRING}

    proxy:
        build:
            context: .
            dockerfile: ./.docker/proxy/Dockerfile
        ports:
            - "8888:80"
        depends_on:
            - database
            - frontend
