name: "tekken-space"

services:
  database:
    image: postgres
    env_file: ./.env.production
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /var/tekken/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    image: ghcr.io/rherwig/tekken-space-web:latest
    ports:
      - "3000:3000"
    depends_on:
      - database

  proxy:
    image: ghcr.io/rherwig/tekken-space-proxy:latest
    ports:
      - "8888:80"
    depends_on:
      - web
