name: "tekken-space"

services:
  database:
    image: postgres
    env_file: ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./var/data:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    env_file: ./.env
    ports:
      - "4200:4200"
    depends_on:
      - database

  storybook:
    build:
      context: .
      dockerfile: ./packages/ui/Dockerfile
    env_file: ./.env
    ports:
      - "3333:3000"

  proxy:
    build: ./.docker/proxy
    ports:
      - "8888:80"
    depends_on:
      - web
      - storybook

  bot:
    build:
      context: .
      dockerfile: ./apps/bot/Dockerfile
    env_file: ./apps/bot/.env
    volumes:
      - /apps/bot/.env:/app/.env
