name: "tekken-space"

services:
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    ports:
      - "3000:3000"

  proxy:
    build:
      context: .
      dockerfile: ./.docker/proxy/Dockerfile
    ports:
      - "8888:80"
    depends_on:
      - web
