export const CHARACTERS = [
    { id: 'alisa', name: 'Alisa', path: 'resources/moves/alisa.json' },
    { id: 'asuka', name: 'Asuka', path: 'resources/moves/asuka.json' },
    { id: 'azucena', name: 'Azucena', path: 'resources/moves/azucena.json' },
    { id: 'bryan', name: 'Bryan', path: 'resources/moves/bryan.json' },
    { id: 'claudio', name: 'Claudio', path: 'resources/moves/claudio.json' },
    {
        id: 'devil-jin',
        name: 'Devil Jin',
        path: 'resources/moves/devil-jin.json',
    },
    { id: 'dragunov', name: 'Dragunov', path: 'resources/moves/dragunov.json' },
    { id: 'eddy', name: 'Eddy', path: 'resources/moves/eddy.json' },
    { id: 'feng', name: 'Feng', path: 'resources/moves/feng.json' },
    { id: 'heihachi', name: 'Heihachi', path: 'resources/moves/heihachi.json' },
    { id: 'hwoarang', name: 'Hwoarang', path: 'resources/moves/hwoarang.json' },
    { id: 'jack-8', name: 'Jack-8', path: 'resources/moves/jack-8.json' },
    { id: 'jin', name: 'Jin', path: 'resources/moves/jin.json' },
    { id: 'jun', name: 'Jun', path: 'resources/moves/jun.json' },
    { id: 'kazuya', name: 'Kazuya', path: 'resources/moves/kazuya.json' },
    { id: 'king', name: 'King', path: 'resources/moves/king.json' },
    { id: 'kuma', name: 'Kuma', path: 'resources/moves/kuma.json' },
    { id: 'lars', name: 'Lars', path: 'resources/moves/lars.json' },
    { id: 'law', name: 'Law', path: 'resources/moves/law.json' },
    { id: 'lee', name: 'Lee', path: 'resources/moves/lee.json' },
    { id: 'leo', name: 'Leo', path: 'resources/moves/leo.json' },
    { id: 'leroy', name: 'Leroy', path: 'resources/moves/leroy.json' },
    { id: 'lidia', name: 'Lidia', path: 'resources/moves/lidia.json' },
    { id: 'lili', name: 'Lili', path: 'resources/moves/lili.json' },
    { id: 'nina', name: 'Nina', path: 'resources/moves/nina.json' },
    { id: 'panda', name: 'Panda', path: 'resources/moves/panda.json' },
    { id: 'paul', name: 'Paul', path: 'resources/moves/paul.json' },
    { id: 'raven', name: 'Raven', path: 'resources/moves/raven.json' },
    { id: 'reina', name: 'Reina', path: 'resources/moves/reina.json' },
    { id: 'shaheen', name: 'Shaheen', path: 'resources/moves/shaheen.json' },
    { id: 'steve', name: 'Steve', path: 'resources/moves/steve.json' },
    { id: 'victor', name: 'Victor', path: 'resources/moves/victor.json' },
    { id: 'xiaoyu', name: 'Xiaoyu', path: 'resources/moves/xiaoyu.json' },
    {
        id: 'yoshimitsu',
        name: 'Yoshimitsu',
        path: 'resources/moves/yoshimitsu.json',
    },
    { id: 'zafina', name: 'Zafina', path: 'resources/moves/zafina.json' },
]
